[project]
name = "mimophys"
description = "A Python library for MIMO systems"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "matplotlib>=3.9",
    "numpy>=1.26",
]
authors=[
    {name="Samuel Li", email="samuel.li@ucla.edu"},
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering",
]
dynamic = ["version"]

license = "MIT"
lisence-file = "LICENSE"

[project.optional-dependencies]
dev = [
    "hatch>=1.14.1",
    "uv>=0.7.13",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "src/mimophys/__about__.py"
